import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora, Playfair_Display } from "next/font/google";
import "./globals.css";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import BannerOferta from "../components/BannerOferta";
import { AuthProvider } from "../context/AuthContext";
import { CartProvider } from "../context/CartContext";
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400","500","600", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
  weight: ["400","500","600", "700"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${lora.variable} antialiased`}
      >
      <AuthProvider>
        <CartProvider>
         <>
          <Banner/>
          <BannerOferta/>
           {children}
          <Footer />
         </>
        </CartProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
